language: csharp
mono: none
dotnet: 3.1.100
dist: xenial

# Install the .NET Core 1.0 runtime as that's what we build and test against
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.0.8
    - dotnet-sharedframework-microsoft.netcore.app-1.1.5
    - dotnet-sdk-2.0.0
    - dotnet-sdk-2.1

script:
  - ./BuildSupport.sh
  - dotnet test Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj --no-build -c Release
  - dotnet test Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj --no-build -c Release
