language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

# Install the .NET Core 1.0 runtime as that's what we test against
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5

script:
  - mkdir -p NuPkgs/Support
  - dotnet --info
  - dotnet restore Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj
  - dotnet restore Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj
  - dotnet build Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj -c Release
  - dotnet build Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj -c Release
  - dotnet test Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj --no-restore --no-build -c Release
  - dotnet test Src/Support/Google.Apis.Auth.Tests/Google.Apis.Auth.Tests.csproj --no-restore --no-build -c Release
