# Configuration for the build and test for the GoogleApis project.

# Version for the build.
version: 1.0.{build}-{branch}

# We're using Visual Studio 2017
image: Visual Studio 2017

# Temporary work around for https://appveyor.statuspage.io/incidents/m2vdvw39kdk8
hosts:
  api.nuget.org: 93.184.221.200

# Install the pre-requisites for the build.
install:
  # Make sure curl is available
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

# Perform the build.
build_script:
  - dotnet --info
  - bash BuildSupport.sh

# Perform the tests. Release build on all supported frameworks.
test_script:
  - dotnet test Src\Support\Google.Apis.Tests\Google.Apis.Tests.csproj --no-build -c Release
  - dotnet test Src\Support\Google.Apis.Auth.Tests\Google.Apis.Auth.Tests.csproj --no-build -c Release
