# Configuration for the build and test for the GoogleApis project.

# Version for the build.
version: 1.0.{build}-{branch}

# We're using Visual Studio 2017
image: Visual Studio 2017

# Install the pre-requisites for the build.
install:
  # Make sure curl is available
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

# Perform the build.
build_script:
  - dotnet --info
  - dotnet restore Src\Support\GoogleApisClient.sln
  - dotnet build Src\Support\GoogleApisClient.sln -c Release

# Perform the tests. Release build on all supported frameworks.
test_script:
  - dotnet test Src\Support\Google.Apis.Tests\Google.Apis.Tests.csproj -c Release
  - dotnet test Src\Support\Google.Apis.Auth.Tests\Google.Apis.Auth.Tests.csproj -c Release
