# Configuration for the build and test for the GoogleApis project.

# Version for the build.
version: 1.0.{build}-{branch}

# We're using Visual Studio 2017
image: Visual Studio 2017

# Install the pre-requisites for the build.
install:
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

# Perform the build.
build_script:
  - mkdir NuPkgs\Support
  - msbuild /version
  - msbuild /t:Restore /m Src\Support
  - msbuild /t:Build /m /p:Platform=x64;Configuration=Debug Src\Support
  - msbuild /t:Build /m /p:Platform=x64;Configuration=Release Src\Support

# Perform the tests. Release build on all supported frameworks.
test_script:
  - dotnet test --no-restore --no-build -c Release Src\Support\Google.Apis.Tests -f netcoreapp1.0
  - dotnet test --no-restore --no-build -c Release Src\Support\Google.Apis.Tests -f net452
  - dotnet test --no-restore --no-build -c Release Src\Support\Google.Apis.Tests -f net46
  - dotnet test --no-restore --no-build -c Release Src\Support\Google.Apis.Auth.Tests -f netcoreapp1.0
  - dotnet test --no-restore --no-build -c Release Src\Support\Google.Apis.Auth.Tests -f net452
  - dotnet test --no-restore --no-build -c Release Src\Support\Google.Apis.Auth.Tests -f net46
