name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:	
      DOTNET_NOLOGO: true

    steps:	
    - uses: actions/checkout@v3
      with:	
        submodules: true	

    # We build with .NET Core 3.1 SDK
    - name: Setup .NET Core 3.1	
      uses: actions/setup-dotnet@v3	
      with:	
        dotnet-version: 3.1.x

    - name: Build and test	
      run: |
        ./BuildSupport.sh
        dotnet test Src/Support/Google.Apis.Tests/Google.Apis.Tests.csproj \
          --no-build --framework netcoreapp3.1 -c Release \
          --logger "console;verbosity=detailed" \
          --filter ResumableUpload
